DROP DATABASE IF EXISTS GUESSDB;

CREATE DATABASE GUESSDB;

use GUESSDB;

CREATE TABLE USER (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASS varchar(60) NOT NULL,
    PRIMARY KEY (USER_ID)
);
CREATE TABLE GUESS (
    GUESS_ID int NOT NULL AUTO_INCREMENT,
    GUESS_AMT int NOT NULL,
    USER_ID int NOT NULL,
    PRIMARY KEY (GUESS_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);
